alias: question
auth_nodes:
    - question.home.get
    - question.question.*
navs:
    Question Manager:
        ord: 99
        children:
            Home:
                app: question
                icon: icon-home
                link: question/home

            Question List:
                app: question
                icon: icon-speedometer
                link: question/question