alias: account
auth_nodes:
    - account.home.get
    - account.profile.put
    - account.userRole.*
    - account.userRole.authorize.put
    - account.userInfo.*
    - account.department.*
navs:
    User Manager:
        children:
            Home:
                app: account
                icon: icon-home
                link: account/home
            Users List:
                app: account
                icon: icon-speedometer
                link: account/userInfo
            Department:
                app: account
                link: account/department
                icon: icon-speedometer
            Role List:
                app: account
                link: account/userRole
                icon: icon-speedometer
