alias: account
navs:
    System Preference:
        children:
            Organization Manage:
                app: account
                icon: nb-gear
                children:
                    Users List:
                        app: account
                        icon: users
                        link: account/userInfo
                    Department:
                        app: account
                        link: account/department
                        icon: sitemap
                    Role List:
                        app: account
                        link: account/rolelist
                        icon: sitemap