alias: product
auth_nodes:
    - product.product.*
    - product.category.*
    - product.tag.*
navs:
    System Manager:
        children:
            Product Manage:
                app: product
                icon: nb-keypad
                children:
                    Product:
                        app: product
                        icon: users
                        link: product/product
                    Category:
                        app: product
                        link: product/category
                        icon: sitemap
                    Tag:
                        app: product
                        icon: male
                        link: product/tag