alias: common
navs:
    System Preference:
        children:
             Data Model Manage:
                app: account
                icon: nb-keypad
                children:
                    Data List:
                        app: account
                        icon: users
                        link: data/userInfo
                    Type List:
                        app: account
                        link: data/department
                        icon: sitemap
             Organization Manage:
                children:
                    Company Profile:
                        app: account
                        link: account/companyProfile